SaleTicketProject/Pages/Contact.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories.IRepository;

namespace SaleTicketProject.Pages
{
    public class ContactModel : PageModel
    {
        private readonly IAccountRepository _accountRepository;
        [BindProperty]
        public Account Account { get; set; }
        [BindProperty]
        public int Id { get; set; }
        public ContactModel(IAccountRepository accountRepository)
        {
            _accountRepository = accountRepository;
        }

        public void OnGet(int ID)
        {
            Account = _accountRepository.GetById(ID)!;
        }

        public IActionResult OnPostHome()
        {
            return RedirectToPage("Index", new { ID = Account.Id });
        }
        public IActionResult OnPostProperties()
        {
            return RedirectToPage("Properties", new { ID = Account.Id });
        }
        public IActionResult OnPostContact()
        {
            return RedirectToPage("Contact", new { ID = Account.Id });
        }
    }
}

SaleTicketProject/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SaleTicketProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

SaleTicketProject/Pages/Index.cshtml.cs
using BusinessObjects;
using DataAccessLayers.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories.IRepository;
using Repositories.Repository;

namespace SaleTicketProject.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IAccountRepository _accountRepository;
        private readonly IEventCategory _eventRepository;

        [BindProperty]
        public Account Account { get; set; }
        public List<Event> Events = new List<Event>();
        public IndexModel(ILogger<IndexModel> logger, IAccountRepository accountRepository, IEventCategory eventRepository)
        {
            _accountRepository = accountRepository;
            _logger = logger;
            _eventRepository = eventRepository;
        }

        public void OnGet(int ID)
        {
            Account = _accountRepository.GetById(ID)!;
            Events = _eventRepository.GetAllInclude().Where(a => a.DateEnd > DateOnly.FromDateTime(DateTime.Now)).ToList();
        }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public int AccountId { get; set; }

        public IActionResult OnPostProperty()
        {
            Account = _accountRepository.GetById(AccountId) ?? throw new Exception();
            return RedirectToPage("Property-details",new { Id = Id, accountId = Account.Id});
        }
        public IActionResult OnPostHome()
        {
            return RedirectToPage("Index",new {ID = Account.Id});
        }
        public IActionResult OnPostProperties()
        {
            return RedirectToPage("Properties", new { ID = Account.Id });
        }
        public IActionResult OnPostContact()
        {
            return RedirectToPage("Contact", new { ID = Account.Id });
        }
        public IActionResult OnPostProfile()
        {

            if (Account == null)
            {
                return NotFound();
            }
            return RedirectToPage("ViewProfile", new { accountId = Account.Id });
        }
    }
}

SaleTicketProject/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories.IRepository;

namespace SaleTicketProject.Pages
{
    public class LoginModel : PageModel
    {
        private readonly IAccountRepository _systemAccountService;
        public LoginModel(IAccountRepository systemAccountService)
        {
            _systemAccountService = systemAccountService;
        }
        [BindProperty]
        public string email { get; set; }
        [BindProperty]
        public string password { get; set; }

        public string message = string.Empty;
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            if (string.IsNullOrEmpty(email))
            {
                TempData["Message"] = "You must enter an Email";
                return Page();
            }

            if (string.IsNullOrEmpty(password))
            {
                TempData["Message"] = "You must enter a Password";
                return Page();
            }

            var memberStaff = _systemAccountService.GetSystemAccountByEmailAndPassword(email, password);
            if (memberStaff == null)
            {
                TempData["Message"] = "Email or Password invalid...";
                return Page();
            }
            if (memberStaff.RoleId == 3 || memberStaff.RoleId == 4)
            {
                TempData["Message"] = "This page is not allow for admin and event operator...";
                return Page();
            }
            if (memberStaff.Status == 0)
            {
                TempData["Message"] = "This account has been banned!";
                return Page();
            }
            if(memberStaff.RoleId == 2)
            {
                return RedirectToPage("./Sponsor/SponsorView", new { ID = memberStaff.Id });
            }
            else
            {
                return RedirectToPage("Index", new { ID = memberStaff.Id });
            }
        }
    }
}

SaleTicketProject/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SaleTicketProject.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

SaleTicketProject/Pages/Properties.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories.IRepository;
using Repositories.Repository;

namespace SaleTicketProject.Pages
{
    public class PropertiesModel : PageModel
    {
        private readonly IEventCategory _eventRepository;
        private readonly IAccountRepository _accountRepository;

        public List<Event> Events = new List<Event>();
        public PropertiesModel(IEventCategory eventRepository, IAccountRepository accountRepository)
        {
            _accountRepository = accountRepository;
            _eventRepository = eventRepository;
        }

        [BindProperty]
        public Account Account { get; set; }
        public void OnGet(int ID)
        {
            Account = _accountRepository.GetById(ID)!;
            Events = _eventRepository.GetAllInclude().Where(a=>a.DateEnd > DateOnly.FromDateTime(DateTime.Now)).ToList();
        }

        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public int AccountId { get; set; }

        public IActionResult OnPostProperty()
        {
            Account = _accountRepository.GetById(AccountId) ?? throw new Exception();
            return RedirectToPage("Property-details", new { Id = Id , accountId = Account.Id });
        }
        public IActionResult OnPostHome()
        {
            Account = Account;
            return RedirectToPage("Index",new { ID = Account!.Id });
        }

        public IActionResult OnPostProperties()
        {
            Account = Account;
            return RedirectToPage(new { ID = Account!.Id });
        }
        public IActionResult OnPostContact()
        {
            Account = Account;
            return RedirectToPage("Contact", new { ID = Account.Id });
        }
    }
}

SaleTicketProject/Pages/Register.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories.IRepository;

namespace SaleTicketProject.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly IAccountRepository _systemAccountService;
        public RegisterModel(IAccountRepository systemAccountService)
        {
            _systemAccountService = systemAccountService;
        }
        [BindProperty]
        public string email { get; set; }
        [BindProperty]
        public string name { get; set; }
        [BindProperty]
        public string address { get; set; }
        [BindProperty]
        public string phone { get; set; }
        [BindProperty]
        public string password { get; set; }
        [BindProperty]
        public string confirm { get; set; }

        public string message = string.Empty;
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            if (string.IsNullOrEmpty(email))
            {
                TempData["Message"] = "You must enter an email";
                return Page();
            }

            if (string.IsNullOrEmpty(password))
            {
                TempData["Message"] = "You must enter a password";
                return Page();
            }
            if (string.IsNullOrEmpty(phone))
            {
                TempData["Message"] = "You must enter an phone";
                return Page();
            }

            if (string.IsNullOrEmpty(address))
            {
                TempData["Message"] = "You must enter a address";
                return Page();
            }
            if (string.IsNullOrEmpty(name))
            {
                TempData["Message"] = "You must enter an name";
                return Page();
            }

            if (string.IsNullOrEmpty(confirm))
            {
                TempData["Message"] = "You must enter a confirm";
                return Page();
            }

            if (confirm != password)
            {
                TempData["Message"] = "Confirm password is not correct";
                return Page();
            }
            var count = _systemAccountService.GetAll().Count();

            var newAccount = new Account()
            {
                Id = count + 1,
                Name = name,
                Address = address,
                Phone = phone,
                Email = email,
                Password = password,
                RoleId = 1,
                Status = 1,
                Wallet=0
            };

            var memberStaff = _systemAccountService.Add(newAccount);
            TempData["Message"] = "Register Successfuly!";
            return RedirectToPage("Login");

        }
    }
}

SaleTicketProject/Pages/ViewHistoryTransaction.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SaleTicketProject.Pages
{
    public class ViewHistoryTransactionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SaleTicketProject/Pages/ViewProfile.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories.IRepository;

namespace SaleTicketProject.Pages
{
    public class ViewProfileModel : PageModel
    {
        private readonly IAccountRepository _account;

        public ViewProfileModel(IAccountRepository account)
        {
            _account = account;
        }
        [BindProperty]
        public Account? Account { get; set; } = null;
        [BindProperty]
        public int AccountId { get; set; }

        [BindProperty]
        public string Password { get; set; }
        public IActionResult OnGet(int accountId)
        {
            Account = _account.GetById(accountId);
            if (Account == null)
            {
                return NotFound();
            }
            return Page();
        }
        public IActionResult OnPostUpdate()
        {
            var existingAccount = _account.GetById(AccountId);
            if (existingAccount == null)
            {
                return NotFound();
            }
            if(Password == null)
            {
                TempData["ErrorMessage"] = "Password is not null!";
                return RedirectToPage(new { accountId = existingAccount.Id });
            }
            existingAccount.Password = Password;
            _account.Update(existingAccount);
            TempData["SuccessMessage"] = "Profile updated successfully!";
            return RedirectToPage(new { accountId = existingAccount.Id });
        }

        public IActionResult OnPostViewHistoryTransaction()
        {
            var existingAccount = _account.GetById(AccountId);
            if (existingAccount == null)
            {
                return NotFound();
            }
            return RedirectToPage("ViewTransactionHIstory", new { accountId = existingAccount.Id });
        }
    }
}

SaleTicketProject/Pages/ViewTransactionHIstory.cshtml.cs
using BusinessObjects;
using BusinessObjects.Enum;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories.IRepository;

namespace SaleTicketProject.Pages
{
    public class ViewTransactionHIstoryModel : PageModel
    {
        private readonly IAccountRepository _account;
        private readonly ITransactionHistoryRepository _transactionHistoryRepository;

        public ViewTransactionHIstoryModel(IAccountRepository account, ITransactionHistoryRepository transactionHistoryRepository)
        {
            _account = account;
            _transactionHistoryRepository = transactionHistoryRepository;
        }
        [BindProperty]
        public Account? Account { get; set; } = null;
        [BindProperty]
        public List<TransactionHistoryDto> TransactionHistory { get; set; }
        [BindProperty]
        public int AccountId { get; set; }

        [BindProperty]
        public string Password { get; set; }
        public IActionResult OnGet(int accountId)
        {
            Account = _account.GetById(accountId);
            if (Account == null)
            {
                return NotFound();
            }
            TransactionHistory = _transactionHistoryRepository.GetAllTransactionHistoryByAccountId(accountId);
            return Page();
        }
    }
}

SaleTicketProject/Pages/Properties.cshtml
@page
@model SaleTicketProject.Pages.PropertiesModel
@{
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="/css/fontawesome.css">
    <link rel="stylesheet" href="/css/templatemo-villa-agency.css">
    <link rel="stylesheet" href="/css/owl.css">
    <link rel="stylesheet" href="/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <!--

    TemplateMo 591 villa agency

    https://templatemo.com/tm-591-villa-agency

    -->
</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->

    <div class="sub-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <ul class="info">
                        <li><i class="fa fa-envelope"></i> CThon@company.com</li>
                        <li><i class="fa fa-map"></i> Thu Duc District, HCM City, VietNam</li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-4">
                    <ul class="social-links">
                        <li><a href="#"><i class="fab fa-facebook"></i></a></li>
                        <li><a href="https://x.com/minthu" target="_blank"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a asp-page="/Index" class="logo">
                            <h1>EVENT</h1>
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <form method="post">
                                @if (Model.Account != null)
                                {
                                    <input type="hidden" asp-for="Id" value="@Model.Account.Id" />
                                }
                            <li><button style="color:white; background:none; border:none" asp-page-handler="Home" type="submit"><a>Home</a></button></li>
                            </form>

                            <form method="post">
                                @if (Model.Account != null)
                                {
                                    <input type="hidden" asp-for="Id" value="@Model.Account.Id" />
                                }
                            <li><button style="color:white; background:none; border:none" asp-page-handler="Properties" type="submit"><a class="active">Properties</a></button></li>
                            </form>


                            <form method="post">
                                @if (Model.Account != null)
                                {
                                    <input type="hidden" asp-for="Id" value="@Model.Account.Id" />
                                }
                            <li><button style="color:white; background:none; border:none" asp-page-handler="Contact" type="submit"><a>Contact Us</a></button></li>
                            </form>



                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <div class="page-heading header-text">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <span class="breadcrumb"><a href="#">Home</a> / Properties</span>
                    <h3>Properties</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="section properties" style="padding-bottom: 100px">
        <div class="container">
            @*             <ul class="properties-filter">
            <li>
            <a class="is_active" href="#!" data-filter="*">Show All</a>
            </li>
            <li>
            <a href="#!" data-filter=".adv">Apartment</a>
            </li>
            <li>
            <a href="#!" data-filter=".str">Villa House</a>
            </li>
            <li>
            <a href="#!" data-filter=".rac">Penthouse</a>
            </li>
            </ul> *@
            <div class="row properties-box">
                @foreach (var article in Model.Events)
                {
                    @if (article.SponsorId != null && article.Status == 1)
                    {
                        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 adv">
                            <div class="item">
                                <form method="post">
                                    @if (Model.Account != null)
                                    {
                                        <input type="hidden" asp-for="AccountId" value="@Model.Account.Id" />
                                    }
                                    <input type="hidden" asp-for="Id" value="@article.Id" />
                                    @if (Model.Account != null)
                                    {
                                        <a asp-page=""><img src="@article.Image" style="height: 258px" alt=""></a>
                                    }
                                    <span class="category">@article.Name</span>
                                    <h6>@article.TicketQuantity</h6>
                                    <h4><a asp-page="">@article.Location</a></h4>
                                    <ul>
                                        <li>Date Start <span>@article.DateStart</span></li>
                                        <li>Date End <span>@article.DateEnd</span></li>
                                        <li>Category <span>@article.CategoryId</span></li>
                                    </ul>
                                    <h4><a style="font-weight:lighter">Sponsor By:</a> @article.Sponsor.Name</h4>
                                    @*                                 <div >
                            <a asp-page="/Property-details">Schedule a visit</a>
                            </div> *@
                                    @if (article.DateStart <= DateOnly.FromDateTime(DateTime.Now))
                                    {
                                        <div class="section-heading text-center">
                                            <h6>ONGOING EVENT CANNOT BUY TICKETS</h6>
                                        </div>
                                        <br/>
                                    }
                                    else if (Model.Account != null)
                                    {
                                        <div class="main-button">
                                            <button type="submit" asp-page-handler="Property" style="border: none"><a style="color: white">Schedule a visit</a></button>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    }
                }

            </div>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="pagination">
                        <li><a href="#">1</a></li>
                        <li><a class="is_active" href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">>></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    @*     <footer>
    <div class="container">
    <div class="col-lg-12">
    <p>
    Copyright © 2048 Villa Agency Co., Ltd. All rights reserved.

    Design: <a rel="nofollow" href="https://templatemo.com" target="_blank">TemplateMo</a>
    </p>
    </div>
    </div>
    </footer> *@

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/isotope.min.js"></script>
    <script src="/js/owl-carousel.js"></script>
    <script src="/js/counter.js"></script>
    <script src="/js/custom.js"></script>

</body>
</html>

SaleTicketProject/Pages/ViewHistoryTransaction.cshtml
@page
@model SaleTicketProject.Pages.ViewHistoryTransactionModel
@{
}

SaleTicketProject/Pages/ViewProfile.cshtml
@page
@model SaleTicketProject.Pages.ViewProfileModel
@{
    ViewData["Title"] = "Profile";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Profile Staff</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <style>
        body {
            background: linear-gradient(45deg, #009fff 50%,#ec2f4b 100%);
            font-family: Arial, sans-serif;
        }

        .container {
            margin: 50px auto;
            background: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .subtitle {
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
            color: #343a40;
        }

        .label {
            font-size: 14px;
            color: #6c757d;
            margin-top: 10px;
            margin-bottom: 5px;
        }

        .textbox {
            width: 100%;
            padding: 10px;
            border: 1px solid #ced4da;
            border-radius: 4px;
            margin-bottom: 10px;
        }

            .textbox:disabled {
                background-color: #e9ecef;
            }

        .button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-top: 10px;
        }

        .button-primary {
            background-color: #007bff;
            color: #ffffff;
        }

        .button-secondary {
            background-color: #6c757d;
            color: #ffffff;
        }

        .button-primary:hover {
            background-color: #0056b3;
        }

        .button-secondary:hover {
            background-color: #5a6268;
        }

        .button-container {
            margin-top: 20px;
            text-align: center;
        }

/*         .alert {
            padding: 15px;
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
            border-radius: 4px;
            margin-bottom: 20px;
        } */

        form {
            max-width: 600px;
            margin: 50px auto;
            margin-left: 300px;
            margin-right: 300px;
            background: #ffffff;
        }

        .alert {
            padding: 20px;
            background-color: #f44336;
            color: white;
            margin-bottom: 15px;
        }

            .alert.success {
                background-color: #4CAF50;
            }

            .alert.info {
                background-color: #2196F3;
            }

            .alert.warning {
                background-color: #ff9800;
            }
    </style>
</head>
<body>
    <div class="container">
        <div class="subtitle">STAFF PROFILE</div>
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert success">
                @TempData["SuccessMessage"]
            </div>
        }
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert">
                @TempData["ErrorMessage"]
            </div>
        }
        <form method="post" id="updateProfileForm">
            <input type="hidden" name="AccountId" asp-for="AccountId" value="@Model.Account.Id" />

            <div class="label">Account Id</div>
            <input type="text" class="textbox" value="@Model.Account.Id" disabled />

            <div class="label">Account Name</div>
            <input type="text" class="textbox"  name="AccountName" value="@Model.Account.Name" disabled />

            <div class="label">Account Email</div>
            <input type="email" class="textbox"  name="AccountEmail" value="@Model.Account.Email" disabled />

            <div class="label">Account Password</div>
            <input type="password" class="textbox" asp-for="Password" name="Password" value="@Model.Account.Password" />

            <div class="label">Wallet</div>
            <input type="number" class="label" name="AccountWallet" value="@Model.Account.Wallet" disabled />

            <button type="submit" class="button button-secondary" asp-page-handler="Update">Update Profile</button>

            <div class="button-container">
                <button class="button button-primary" asp-page-handler="ViewHistoryTransaction">View History Transaction</button>
            </div>
        </form>
    </div>
    @section Scripts {
        <script>
            function updateProfile() {
                fetch('@Url.Page("StaffScreen", "UpdateProfile")', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'RequestVerificationToken': document.querySelector('input[name="__RequestVerificationToken"]').value
                    },
                    body: JSON.stringify({
                        AccountId: parseInt(document.querySelector('input[name="AccountId"]').value),
                        AccountName: document.querySelector('input[name="AccountName"]').value,
                        AccountEmail: document.querySelector('input[name="AccountEmail"]').value,
                        AccountPassword: document.querySelector('input[name="AccountPassword"]').value
                        AccountWallet: document.querySelector('input[name="AccountWallet"]').value
                    })
                }).then(response => response.json()).then(data => {
                    if (data.success) {
                        alert('Update completed!');
                    } else {
                        alert('Update failed!');
                    }
                });
            }
        </script>
    }
</body>
</html>